

/*7.1*/
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL 
FROM EMPLOYEE 
WHERE EMP_LNAME 
LIKE '%Smith%' ORDER BY EMP_NUM

/*7.2*/
SELECT	PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, 
    EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMPLOYEE.JOB_CODE, 
    JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR
FROM	PROJECT, EMPLOYEE, JOB
WHERE	EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM
AND	JOB.JOB_CODE = EMPLOYEE.JOB_CODE;

/*7.3*/
SELECT	PROJ_NAME, PROJ_VALUE, PROJ_BALANCE, 
    EMPLOYEE.EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMPLOYEE.JOB_CODE, 
    JOB.JOB_DESCRIPTION, JOB.JOB_CHG_HOUR
FROM	PROJECT, EMPLOYEE, JOB
WHERE	EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM
AND	JOB.JOB_CODE = EMPLOYEE.JOB_CODE
ORDER BY EMPLOYEE.EMP_LNAME

/*7.5*/
SELECT ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, 
    ROUND(ASSIGN_CHG_HR * ASSIGN_HOURS,2) AS CAL_ASSIGN_CHARGE 
FROM ASSIGNMENT 
ORDER BY ASSIGN_NUM

/*7.6*/
SELECT	ASSIGNMENT.EMP_NUM, EMPLOYEE.EMP_LNAME, 
    Sum(ASSIGNMENT.ASSIGN_HOURS) AS SumOfASSIGN_HOURS, 
    Sum(ASSIGNMENT.ASSIGN_CHARGE) AS SumOfASSIGN_CHARGE
FROM    EMPLOYEE, ASSIGNMENT
WHERE   EMPLOYEE.EMP_NUM = ASSIGNMENT.EMP_NUM
GROUP BY    ASSIGNMENT.EMP_NUM, EMPLOYEE.EMP_LNAME
ORDER BY ASSIGNMENT.EMP_NUM;

/*7.7*/
SELECT  ASSIGNMENT.PROJ_NUM, 
    Sum(ASSIGNMENT.ASSIGN_HOURS) AS SumOfASSIGN_HOURS,
    Sum(ASSIGNMENT.ASSIGN_CHARGE) AS SumOfASSIGN_CHARGE
FROM    ASSIGNMENT
GROUP BY    ASSIGNMENT.PROJ_NUM

/*8.1*/
CREATE TABLE EMP_1 (
EMP_NUM CHAR(3) PRIMARY KEY,
EMP_LNAME   VARCHAR(15) NOT NULL,
EMP_FNAME   VARCHAR(15) NOT NULL,
EMP_INITIAL CHAR(1),
EMP_HIREDATE    DATE,
JOB_CODE    CHAR(3),
FOREIGN KEY (JOB_CODE) REFERENCES JOB);

/*8.2*/
INSERT INTO EMP_1 VALUES ('101', 'News', 'John', 'G', '08-Nov-00', '502');
INSERT INTO EMP_1 VALUES ('102', 'Senior', 'David', 'H', '12-Jul-89', '501');

/*8.5*/
UPDATE EMP_1
SET	JOB_CODE = '501'
WHERE	EMP_NUM = '107';

/*8.6*/
DELETE	FROM EMP_1
WHERE	EMP_LNAME = 'Smithfield'
AND	EMP_FNAME = 'William'
AND	EMP_HIREDATE = '22-June-04'
AND	JOB_CODE = '500';
